version: "3.2"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    restart: unless-stopped
    command: elasticsearch
    ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"
    expose:
      - "9200"
      - "9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g

  starchat:
    image: java:8
    restart: unless-stopped
    command: ["/starchat/scripts/utils/wait-for-it.sh", "getjenny-es", "9200", "10", "/starchat/bin/starchat"]
    volumes:
      - ./starchat:/starchat
    ports:
      - "0.0.0.0:8888:8888"
      - "0.0.0.0:8443:8443"
    links:
      - "elasticsearch:getjenny-es"
  starchat2:
    image: java:8
    restart: unless-stopped
    command: ["/starchat/scripts/utils/wait-for-it.sh", "getjenny-es", "9200", "10", "/starchat/bin/starchat"]
    volumes:
      - ./starchat2:/starchat
    ports:
      - "0.0.0.0:8889:8888"
      - "0.0.0.0:8444:8443"
    links:
      - "elasticsearch:getjenny-es"
