version: "3.2"
services:

  elasticsearch:
    image: elasticsearch:5.4.2
    command: elasticsearch
    ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"
    expose:
      - "9200"
      - "9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g

  starchat:
    image: java:8
    command: /starchat/bin/starchat
    volumes:
      - ./starchat:/starchat
    ports:
      - "0.0.0.0:8888:8888"
      - "0.0.0.0:8443:8443"
    links:
      - "elasticsearch:getjenny-es"

  manaus:
    image: elegansio/manaus:1.0.1
    restart: unless-stopped
    volumes:
      - ./manaus/data:/manaus/data
      - ./manaus/log:/manaus/log
    command: ["/manaus/scripts/wait-for-it.sh", "getjenny-es", "9300", "10", "/manaus/bin/continuous-keywords-update", "--temp_data_folder", "/manaus/data", "--host_map", "getjenny-es=9300", "--interval_sec", "14400", "--word_frequencies", "/manaus/statistics_data/english/word_frequency.tsv", "--cluster_name", "starchat", "--index_name", "jenny-en-0"]
    links:
      - "starchat:starchat"
      - "elasticsearch:getjenny-es"

