version: "3.2"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    restart: unless-stopped
    command: elasticsearch
    ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"
    expose:
      - "9200"
      - "9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    environment:
      - MAX_LOCKED_MEMORY=unlimited

  starchat:
    image: java:8
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: ["/starchat/scripts/utils/wait-for-it.sh", "getjenny-es", "9200", "10", "/starchat/bin/starchat"]
    volumes:
      - ./starchat:/starchat
    ports:
      - "0.0.0.0:8888:8888"
      - "0.0.0.0:8443:8443"
    links:
      - "elasticsearch:getjenny-es"

  manaus:
    image: elegansio/manaus:2.0.3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    volumes:
      - ./manaus/data:/manaus/data
      - ./manaus/log:/manaus/log
    command: ["/manaus/scripts/wait-for-it.sh", "getjenny-es", "9200", "5", "/manaus/bin/continuous-keywords-update-all-indexes", "--temp_data_folder", "manaus/data", "--host_map", "getjenny-es=9300", "--interval_sec", "5", "--word_frequencies", "manaus/statistics_data", "--cluster_name", "starchat"]      
    links:
      - "starchat:starchat"
      - "elasticsearch:getjenny-es"

